app <- ShinyDriver$new("../")
app$snapshotInit("hier_labels")

app$setInputs(addin_tabs = "Hierarchical ID Code Generation")
app$setInputs(hier_prefix = "a", wait_=FALSE, values_=FALSE)
app$setInputs(hier_start_number = character(0), wait_=FALSE, values_=FALSE)
app$setInputs(hier_start_number = 1, wait_=FALSE, values_=FALSE)
app$setInputs(hier_end_number = character(0), wait_=FALSE, values_=FALSE)
app$setInputs(hier_end_number = 2, wait_=FALSE, values_=FALSE)
app$setInputs(insertBtn = "click")
app$snapshot()
app$setInputs(hier_prefix = "b", wait_=FALSE, values_=FALSE)
app$setInputs(hier_start_number = 1, wait_=FALSE, values_=FALSE)
app$setInputs(hier_end_number = 3, wait_=FALSE, values_=FALSE)
app$setInputs(insertBtn = "click")
app$setInputs(hier_label_df_rows_current = c(1, 2, 3, 4, 5, 6), allowInputNoBinding_ = TRUE)
app$setInputs(hier_label_df_rows_all = c(1, 2, 3, 4, 5, 6), allowInputNoBinding_ = TRUE, wait_=FALSE, values_=FALSE)
app$snapshot()
