app <- ShinyDriver$new("../")
app$snapshotInit("test_bar")

app$setInputs(addin_tabs = "Barcode Creation")
app$uploadFile(labels = "test_labels.csv")
app$setInputs(label_check = "click")
app$snapshot(list(output = "label_preview"))
app$setInputs(type = "linear")
app$snapshot(list(output = "label_preview"))
app$setInputs(font_size = 12)
app$snapshot(list(output = "label_preview"))
app$setInputs(check_make_labels_columns_selected = 2, allowInputNoBinding_ = TRUE)
app$setInputs(check_make_labels_cell_clicked = c("2", "2", "a01"), allowInputNoBinding_ = TRUE)
app$snapshot(list(output = "label_preview"))
